version: "3.4"

name: ugd

services:
  mysql:
    container_name: ugd-mysql
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ugd}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-sukun031015}
    volumes:
      - mysql:/var/lib/mysql/
      - ./sql/mysql:/docker-entrypoint-initdb.d:ro

  redis:
    container_name: ugd-redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  neo4j:
    container_name: ugd-neo4j
    image: neo4j:2025.02
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH:-neo4j/sukun031015}
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.cypher.*"
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j:/data



#  server:
#    container_name: ugd-server
#    build:
#      context: ./ugd-server/
#    image: ugd-server
#    restart: unless-stopped
#    ports:
#      - "48080:48080"
#    environment:
#      # https://github.com/polovyivan/docker-pass-configs-to-container
#      SPRING_PROFILES_ACTIVE: local
#      JAVA_OPTS:
#        ${JAVA_OPTS:-
#          -Xms512m
#          -Xmx512m
#          -Djava.security.egd=file:/dev/./urandom
#        }
#      ARGS:
#        --spring.datasource.dynamic.datasource.master.url=${MASTER_DATASOURCE_URL:-jdbc:mysql://ugd-mysql:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
#        --spring.datasource.dynamic.datasource.master.username=${MASTER_DATASOURCE_USERNAME:-root}
#        --spring.datasource.dynamic.datasource.master.password=${MASTER_DATASOURCE_PASSWORD:-123456}
#        --spring.datasource.dynamic.datasource.slave.url=${SLAVE_DATASOURCE_URL:-jdbc:mysql://ugd-mysql:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
#        --spring.datasource.dynamic.datasource.slave.username=${SLAVE_DATASOURCE_USERNAME:-root}
#        --spring.datasource.dynamic.datasource.slave.password=${SLAVE_DATASOURCE_PASSWORD:-123456}
#        --spring.data.redis.host=${REDIS_HOST:-ugd-redis}
#    depends_on:
#      - mysql
#      - redis
#
#  admin:
#    container_name: ugd-admin
#    build:
#      context: ./ugd-ui-admin
#      args:
#        NODE_ENV:
#          ENV=${NODE_ENV:-production}
#          PUBLIC_PATH=${PUBLIC_PATH:-/}
#          VUE_APP_TITLE=${VUE_APP_TITLE:-中医问诊系统}
#          VUE_APP_BASE_API=${VUE_APP_BASE_API:-/prod-api}
#          VUE_APP_APP_NAME=${VUE_APP_APP_NAME:-/}
#          VUE_APP_CAPTCHA_ENABLE=${VUE_APP_CAPTCHA_ENABLE:-true}
#          VUE_APP_DOC_ENABLE=${VUE_APP_DOC_ENABLE:-true}
#          VUE_APP_BAIDU_CODE=${VUE_APP_BAIDU_CODE:-fadc1bd5db1a1d6f581df60a1807f8ab}
#    image: ugd-admin
#    restart: unless-stopped
#    ports:
#      - "8080:80"
#    depends_on:
#      - server

volumes:
  mysql:
    driver: local
  redis:
    driver: local
  neo4j:
    driver: local
